apiVersion: v1
data:
  OPERATIONAL_MODE: CLUSTERED_CONSOLE
  PA_ADMIN_PRIVATE_HOSTNAME: PA_ADM_SVC_NAME
  PING_IDENTITY_ACCEPT_EULA: "YES"
  #VERBOSE: "true"
  HEAP_MIN: 500m
  HEAP_MAX: 1g
  NR_AGENT: ""
  PA_CONFIG_QUERY_KEYPAIR_ID: "9"
  PA_ADM_NAME: "pingaccess-admin"

  
  #Base Profile - Pulls config relevant to conf and data directories
  SERVER_PROFILE_URL: https://068bceabb129402e0e007dd6908ec23380da17ba@git.nylcloud.com/ECS/nylpadev
  SERVER_PROFILE_PATH: layered-profiles/pingaccess
  SERVER_PROFILE_PARENT: ADMIN
  
  
  SERVER_PROFILE_ADMIN_PATH: layered-profiles/pingaccessadmin
  SERVER_PROFILE_ADMIN_URL: https://068bceabb129402e0e007dd6908ec23380da17ba@git.nylcloud.com/ECS/nylpadev
kind: ConfigMap
metadata:
  name: pingaccess-admin-environment-variables-PA_SVC_VERSION
  namespace: "paapps"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    role: pingaccess
    tier: console
  name: PA_ADM_SVC_NAME
  namespace: "paapps"
spec:
  ports:
  - name: console
    port: 9000
  - name: cluster
    port: 9090
  selector:
    role: pingaccess
    tier: console
    version: "PA_SVC_VERSION"
  type: NodePort   
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    role: pingaccess
    tier: console
  name: pingaccess-admin-PA_SVC_VERSION
  namespace: "paapps"
spec:
  replicas: 1
  selector:
    matchLabels:
      role: pingaccess
      tier: console
      version: "PA_SVC_VERSION"
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate    
  template:
    metadata:
      labels:
        role: pingaccess
        tier: console
        version: "PA_SVC_VERSION"
      name: pingaccess-admin-PA_SVC_VERSION
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: pingaccess-admin-environment-variables-PA_SVC_VERSION
            #- secretRef:
            #name: devops-secret
            #optional: true
        image: pingidentity/pingaccess:6.3.2-edge
        name: pingaccess-admin
        ports:
        - containerPort: 9000
        - containerPort: 9090
        resources:
          limits:
            cpu: "0.5"
            memory: 3G
          requests:
            cpu: "0.5"
            memory: 3G
